### ISSUE TITLE
Instalação do bootstrap, não aparecem as pastas

### ISSUE THREAD

**Issue by EduradoPessoa** [glaucia86/tutorial-crud-mean#2]
Olá Gláucia,
Parabéns pelos videos, são fantásticos.

Ao instalar o bootstrap dentro da pasta front, no diretório node_modules/bootstrap, só aparecem os arquivos package.json e README.md.
Já apaguei o node_modules, rodei o fix, nada faz aparecer essas pastas.

Pode me ajudar?

**Comment by glaucia86** [comment]
> Olá Gláucia,
> Parabéns pelos videos, são fantásticos.
> 
> Ao instalar o bootstrap dentro da pasta front, no diretório node_modules/bootstrap, só aparecem os arquivos package.json e README.md.
> Já apaguei o node_modules, rodei o fix, nada faz aparecer essas pastas.
> 
> Pode me ajudar?

Sim, claro. Você tem o seu código disponível no Githug para que eu possa dar uma olhada e ver o que está acontecendo? Se não, crie um repo para que eu possa dar uma olhada. ;)
