### ISSUE TITLE
Continuidade do Curso

### ISSUE THREAD

**Issue by BrunoBonadiman** [glaucia86/tutorial-crud-mean#3]
Boa Tarde Glaucia!

Primeiramente parabéns pelo curso, tem me ajudado muito. Obrigado por compartilhar o seu conhecimento com a gente.

Gostaria de saber se o curso terá continuidade na parte do front? Se eu não me engano ainda faltando o listar, editar e deletar!

**Comment by glaucia86** [comment]
Boa tarde Bruno. Tudo bem? Terá sim. Na parte do front voltaremos e irei tratar justo a integração da api criada no Back-End em conjunto com o Front-End. Assim que aguarde pelos próximos vídeos! :)

cc: @BrunoBonadiman

**Comment by BrunoBonadiman** [comment]
Obrigado!

Como base nas aulas que você tem ministrado, eu sou criando um projeto
individual com angular 8 para treinamento.

Está me ajudando muito.

Em seg, 5 de ago de 2019 15:08, Glaucia Lemos <notifications@github.com>
escreveu:
