### ISSUE TITLE
os comandos ng nao funcionam

### ISSUE THREAD

**Issue by Bobsp2018** [glaucia86/tutorial-crud-mean#7]
![Screenshot_1](https://user-images.githubusercontent.com/42824148/69271002-dc84db00-0bb2-11ea-9cf5-ba048a0b1a99.jpg)

**Comment by glaucia86** [comment]
@Bobsp2018 parece q vc não está com o teu Angular instalado na sua máquina. Já procurou averiguar isso? Já conseguiu executar os comandos?

**Comment by glaucia86** [comment]
fechando a issue
